import { logger } from '../utils/logger.js';

/**
 * Escape special LaTeX characters.
 */
function esc(str) {
  if (!str) return '';
  return String(str)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/</g, '\\textless{}')
    .replace(/>/g, '\\textgreater{}')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}');
}

function safeBullet(b) {
  return `    \\resumeItem{${esc(b)}}`;
}

function experienceBlock(exp) {
  const bullets = (exp.bullets || []).map(safeBullet).join('\n');
  return `
  \\resumeSubheading
    {${esc(exp.company)}}{${esc(exp.location || '')}}
    {${esc(exp.title)}}{${esc(exp.dates || '')}}
    \\resumeItemListStart
${bullets}
    \\resumeItemListEnd`;
}

function educationBlock(edu) {
  const extra = [];
  if (edu.gpa) extra.push(`GPA: ${esc(edu.gpa)}`);
  if (edu.relevant_courses) extra.push(`Relevant Courses: ${esc(edu.relevant_courses)}`);
  return `
  \\resumeSubheading
    {${esc(edu.institution)}}{${esc(edu.location || '')}}
    {${esc(edu.degree)}}{${esc(edu.dates || '')}}${
  extra.length
    ? `\n    \\resumeItemListStart\n      \\resumeItem{${extra.join(' | ')}}\n    \\resumeItemListEnd`
    : ''
}`;
}

function projectBlock(proj) {
  const techStr = proj.tech ? ` $|$ \\emph{${esc(proj.tech)}}` : '';
  const linkStr = proj.link ? ` $|$ \\href{${esc(proj.link)}}{\\underline{GitHub}}` : '';
  const bullets = (proj.bullets || []).map(safeBullet).join('\n');
  return `
  \\resumeProjectHeading
    {\\textbf{${esc(proj.name)}}${techStr}${linkStr}}{${esc(proj.dates || '')}}
    \\resumeItemListStart
${bullets}
    \\resumeItemListEnd`;
}

function skillsBlock(skills) {
  if (!skills) return '';
  if (Array.isArray(skills)) {
    return `    \\small{\\item{\\textbf{Technical Skills:}{ ${skills.map(esc).join(', ')} }}}`;
  }
  const lines = [];
  if (skills.languages?.length) lines.push(`\\textbf{Languages:}{ ${skills.languages.map(esc).join(', ')} }`);
  if (skills.frameworks?.length) lines.push(`\\textbf{Frameworks \\& Libraries:}{ ${skills.frameworks.map(esc).join(', ')} }`);
  if (skills.databases?.length) lines.push(`\\textbf{Databases:}{ ${skills.databases.map(esc).join(', ')} }`);
  if (skills.tools?.length) lines.push(`\\textbf{Tools \\& Platforms:}{ ${skills.tools.map(esc).join(', ')} }`);
  if (skills.other?.length) lines.push(`\\textbf{Other:}{ ${skills.other.map(esc).join(', ')} }`);
  return lines.map((l) => `    \\small{\\item{${l}}}`).join('\n');
}

/**
 * Generate full LaTeX source using the Audric Serador (sb2nov) template.
 */
export function generateLatex(data) {
  const name = esc(data.name || 'Full Name');
  const email = data.email || '';
  const phone = esc(data.phone || '');
  const location = esc(data.location || '');
  const linkedin = data.linkedin || '';
  const github = data.github || '';
  const portfolio = data.portfolio || '';

  const contactItems = [];
  if (phone) contactItems.push(`\\faPhone\\ ${phone}`);
  if (email) contactItems.push(`\\href{mailto:${email}}{\\faEnvelope\\ \\underline{${esc(email)}}}`);
  if (linkedin) contactItems.push(`\\href{${linkedin}}{\\faLinkedin\\ \\underline{LinkedIn}}`);
  if (github) contactItems.push(`\\href{${github}}{\\faGithub\\ \\underline{GitHub}}`);
  if (portfolio) contactItems.push(`\\href{${portfolio}}{\\faGlobe\\ \\underline{Portfolio}}`);
  if (location) contactItems.push(location);
  
  const contactLine = contactItems.join(' ~ $|$ ~ ');

  const education = (data.education || []).map(educationBlock).join('\n');
  const experience = (data.experience || []).map(experienceBlock).join('\n');
  const projects = (data.projects || []).map(projectBlock).join('\n');

  const latex = `%==================================================
% ATS-Optimised Resume — Generated by ResumeBot
% Template: Audric Serador / sb2nov
%==================================================
\\documentclass[letterpaper,11pt]{article}

\\usepackage{fontawesome5}
\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

% Custom font
\\usepackage[default]{lato}

\\pagestyle{fancy}
\\fancyhf{} % clear all header and footer fields
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule\\vspace{-5pt}]

% Ensure machine readable
\\pdfgentounicode=1

%---------- CUSTOM COMMANDS ----------
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-5pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%========================================
\\begin{document}

%---------- HEADING ----------
\\begin{center}
    {\\Huge \\scshape ${name}} \\\\ \\vspace{1pt}
    \\small ${contactLine}
\\end{center}

%-----------Summary-----------
${data.summary ? `\\section{Professional Summary}\n  \\small{${esc(data.summary)}}\n` : ''}

%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
${education}
  \\resumeSubHeadingListEnd

%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
${experience}
  \\resumeSubHeadingListEnd
${
  data.projects?.length
    ? `
%-----------PROJECTS-----------
\\section{Projects}
  \\resumeSubHeadingListStart
${projects}
  \\resumeSubHeadingListEnd`
    : ''
}

%-----------TECHNICAL SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
${skillsBlock(data.skills)}
    }}
 \\end{itemize}

\\end{document}
`;

  logger.info('LaTeX generated successfully using template: Deepak ATS Friendly Resume');
  return latex;
}

