import os
import subprocess
import shutil
import pathlib
from config import config
from utils.logger import logger

class LatexGenerator:
    def __init__(self, template_path=None):
        self.template_path = template_path
        # Common locations for Edge
        self.edge_paths = [
            r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
            r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
            shutil.which("msedge")
        ]
        self._set_edge_path()

    def _set_edge_path(self):
        self.active_edge = None
        for p in self.edge_paths:
            if p and os.path.exists(p):
                self.active_edge = p
                break

    def esc(self, text):
        """Escape special LaTeX characters."""
        if not text: return ""
        replacements = {
            '\\': r'\textbackslash{}',
            '&': r'\&',
            '%': r'\%',
            '$': r'\$',
            '#': r'\#',
            '_': r'\_',
            '{': r'\{',
            '}': r'\}',
            '~': r'\textasciitilde{}',
            '^': r'\textasciicircum{}',
            '<': r'\textless{}',
            '>': r'\textgreater{}',
        }
        for char, replacement in replacements.items():
            text = str(text).replace(char, replacement)
        return text

    def generate_latex(self, data):
        """
        Generate self-contained LaTeX source using the ATS-Friendly template logic.
        """
        name = self.esc(data.get('name', 'Full Name'))
        email = data.get('email', '')
        phone = self.esc(data.get('phone', ''))
        location = self.esc(data.get('location', ''))
        linkedin = data.get('linkedin', '')
        github = data.get('github', '')
        
        contact_items = []
        if phone: contact_items.append(f"\\faPhone\\ {phone}")
        if email: contact_items.append(f"\\href{{mailto:{email}}}{{\\faEnvelope\\ \\underline{{{self.esc(email)}}}}}")
        if linkedin: contact_items.append(f"\\href{{{linkedin}}}{{\\faLinkedin\\ \\underline{{LinkedIn}}}}")
        if github: contact_items.append(f"\\href{{{github}}}{{\\faGithub\\ \\underline{{GitHub}}}}")
        if location: contact_items.append(location)
        
        contact_line = " ~ $|$ ~ ".join(contact_items)

        experience_blocks = []
        for exp in data.get('experience', []):
            bullets = "\n".join([f"    \\resumeItem{{{self.esc(b)}}}" for b in exp.get('bullets', [])])
            block = f"""
  \\resumeSubheading
    {{{self.esc(exp.get('company',''))}}}{{{self.esc(exp.get('location', ''))}}}
    {{{self.esc(exp.get('title',''))}}}{{{self.esc(exp.get('dates', ''))}}}
    \\resumeItemListStart
{bullets}
    \\resumeItemListEnd"""
            experience_blocks.append(block)
        experience_content = "\n".join(experience_blocks)

        education_blocks = []
        for edu in data.get('education', []):
            block = f"""
  \\resumeSubheading
    {{{self.esc(edu.get('institution',''))}}}{{{self.esc(edu.get('location', ''))}}}
    {{{self.esc(edu.get('degree',''))}}}{{{self.esc(edu.get('dates', ''))}}}"""
            education_blocks.append(block)
        education_content = "\n".join(education_blocks)

        project_blocks = []
        for proj in data.get('projects', []):
            bullets = "\n".join([f"    \\resumeItem{{{self.esc(b)}}}" for b in proj.get('bullets', [])])
            block = f"""
  \\resumeProjectHeading
    {{\\textbf{{{self.esc(proj.get('name',''))}}}}}{{{self.esc(proj.get('dates', ''))}}}
    \\resumeItemListStart
{bullets}
    \\resumeItemListEnd"""
            project_blocks.append(block)
        project_content = "\n".join(project_blocks)

        skills = data.get('skills', [])
        if isinstance(skills, list):
            skills_content = f"    \\small{{\\item{{\\textbf{{Technical Skills:}}{{ {', '.join([self.esc(s) for s in skills])} }}}}"
        else:
            skills_content = f"    \\small{{\\item{{\\textbf{{Technical Skills:}}{{ {self.esc(str(skills))} }}}}"

        # Raw string for template to avoid f-string escaping nightmare
        template = r"""%==================================================
% ATS-Optimised Resume — Generated by ResumeBot (Python)
%==================================================
\documentclass[letterpaper,11pt]{article}

\usepackage{fontawesome5}
\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

% Custom font
\usepackage[default]{lato}

\pagestyle{fancy}
\fancyhf{} % clear all header and footer fields
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule\vspace{-5pt}]

% Ensure machine readable
\pdfgentounicode=1

%---------- CUSTOM COMMANDS ----------
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-5pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}
\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

%========================================
\begin{document}

%---------- HEADING ----------
\begin{center}
    {\Huge \scshape {{NAME}}} \\ \vspace{1pt}
    \small {{CONTACT_LINE}}
\end{center}

%-----------Summary-----------
{{SUMMARY_SECTION}}

%-----------EDUCATION-----------
\section{Education}
  \resumeSubHeadingListStart
{{EDUCATION_CONTENT}}
  \resumeSubHeadingListEnd

%-----------EXPERIENCE-----------
\section{Experience}
  \resumeSubHeadingListStart
{{EXPERIENCE_CONTENT}}
  \resumeSubHeadingListEnd

%-----------PROJECTS-----------
\section{Projects}
  \resumeSubHeadingListStart
{{PROJECT_CONTENT}}
  \resumeSubHeadingListEnd

%-----------TECHNICAL SKILLS-----------
\section{Technical Skills}
 \begin{itemize}[leftmargin=0.15in, label={}]
    {{SKILLS_CONTENT}}
 \end{itemize}

\end{document}
"""
        summary_sect = f"\\section{{Professional Summary}}\n  \\small{{{self.esc(data.get('summary', ''))}}}" if data.get('summary') else ""
        
        latex = template.replace("{{NAME}}", name)
        latex = latex.replace("{{CONTACT_LINE}}", contact_line)
        latex = latex.replace("{{SUMMARY_SECTION}}", summary_sect)
        latex = latex.replace("{{EDUCATION_CONTENT}}", education_content)
        latex = latex.replace("{{EXPERIENCE_CONTENT}}", experience_content)
        latex = latex.replace("{{PROJECT_CONTENT}}", project_content)
        latex = latex.replace("{{SKILLS_CONTENT}}", skills_content)
        
        return latex

    def compile_pdf(self, tex_content, output_name, raw_data=None):
        """Compile .tex to PDF. Falls back to HTML-to-PDF if pdflatex fails."""
        if not tex_content: return None, None
        
        os.makedirs(config.TEMP_DIR, exist_ok=True)
        temp_tex_path = os.path.join(config.TEMP_DIR, f"{output_name}.tex")
        pdf_path = os.path.join(config.TEMP_DIR, f"{output_name}.pdf")

        try:
            with open(temp_tex_path, 'w', encoding='utf-8') as f:
                f.write(tex_content)

            # 1. Try pdflatex
            subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", f"-output-directory={config.TEMP_DIR}", temp_tex_path],
                capture_output=True,
                text=True,
                timeout=60
            )
            
            if os.path.exists(pdf_path) and os.path.getsize(pdf_path) > 1000:
                logger.info(f"PDF compiled successfully with pdflatex: {pdf_path}")
                return temp_tex_path, pdf_path
        except Exception as e:
            logger.warning(f"pdflatex failed or not found: {str(e)}")

        # 2. Fallback: HTML to PDF via Edge
        if raw_data:
            logger.info("Starting HTML-to-PDF fallback...")
            try:
                html_file = self.generate_html(raw_data, output_name)
                fallback_pdf = self.convert_html_to_pdf_edge(html_file, pdf_path)
                if fallback_pdf:
                    logger.info(f"PDF generated via HTML fallback: {fallback_pdf}")
                    return temp_tex_path, fallback_pdf
            except Exception as e:
                logger.error(f"Fallback PDF generation failed: {str(e)}")

        return temp_tex_path, None

    def generate_html(self, data, output_name):
        """Generate a basic but clean HTML version for fallback."""
        html_path = os.path.join(config.TEMP_DIR, f"{output_name}.html")
        
        name = data.get('name', 'Full Name')
        summary = data.get('summary', '')
        
        skills = data.get('skills', [])
        skills_html = ", ".join(skills) if isinstance(skills, list) else str(skills)
        
        exp_html = ""
        for exp in data.get('experience', []):
            bullets = "".join([f"<li>{b}</li>" for b in exp.get('bullets', [])])
            exp_html += f"<div><h3 style='margin-bottom:0;'>{exp.get('title')}</h3><p style='margin:0;'><b>{exp.get('company')}</b> | <i>{exp.get('dates')}</i></p><ul>{bullets}</ul></div>"

        edu_html = ""
        for edu in data.get('education', []):
            edu_html += f"<div><h3 style='margin-bottom:0;'>{edu.get('institution')}</h3><p style='margin:0;'>{edu.get('degree')} | {edu.get('dates')}</p></div>"

        proj_html = ""
        for proj in data.get('projects', []):
            bullets = "".join([f"<li>{b}</li>" for b in proj.get('bullets', [])])
            proj_html += f"<div><h3 style='margin-bottom:0;'>{proj.get('name')}</h3><p style='margin:0;'><i>{proj.get('dates')}</i></p><ul>{bullets}</ul></div>"

        html_content = f"""
        <html>
        <head>
            <style>
                @page {{ margin: 0.5in; }}
                body {{ font-family: 'Helvetica', 'Arial', sans-serif; line-height: 1.4; color: #333; }}
                h1 {{ border-bottom: 2px solid #000; padding-bottom: 10px; text-align: center; text-transform: uppercase; margin-bottom: 5px; }}
                h2 {{ border-bottom: 1px solid #999; margin-top: 20px; text-transform: uppercase; color: #000; font-size: 1.1em; margin-bottom: 10px; }}
                h3 {{ font-size: 1.05em; color: #111; }}
                p, li {{ font-size: 10pt; }}
                .contact {{ text-align: center; margin-bottom: 20px; font-size: 9pt; }}
                .section {{ margin-bottom: 15px; }}
                ul {{ margin-top: 5px; padding-left: 20px; }}
            </style>
        </head>
        <body>
            <h1>{name}</h1>
            <div class="contact">{data.get('email', '')} | {data.get('phone', '')} | {data.get('linkedin', '')}</div>
            {f"<div class='section'><h2>Professional Summary</h2><p>{summary}</p></div>" if summary else ""}
            <div class="section"><h2>Technical Skills</h2><p>{skills_html}</p></div>
            <div class="section"><h2>Experience</h2>{exp_html}</div>
            <div class="section"><h2>Projects</h2>{proj_html}</div>
            <div class="section"><h2>Education</h2>{edu_html}</div>
        </body>
        </html>
        """
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        return html_path

    def convert_html_to_pdf_edge(self, html_path, pdf_path):
        """Convert HTML to PDF using Microsoft Edge headless."""
        if not self.active_edge:
            logger.error("Microsoft Edge not found on this system.")
            return None
            
        try:
            html_url = pathlib.Path(os.path.abspath(html_path)).as_uri()
            cmd = [
                self.active_edge,
                "--headless",
                "--disable-gpu",
                "--no-sandbox",
                f"--print-to-pdf={os.path.abspath(pdf_path)}",
                html_url
            ]
            subprocess.run(cmd, timeout=30, check=True, capture_output=True)
            if os.path.exists(pdf_path) and os.path.getsize(pdf_path) > 100:
                return pdf_path
        except Exception as e:
            logger.error(f"Edge conversion error: {str(e)}")
        return None

latex_generator = LatexGenerator()
